# Generated by Django 3.2.3 on 2023-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluser',
            name='usr_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
