# Generated by Django 4.2.3 on 2023-07-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelPsmtRequestModules',
            fields=[
                ('request_package_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_ref_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('package_id', models.CharField(blank=True, max_length=255, null=True)),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('module_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('module_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_module_id', models.CharField(blank=True, max_length=255, null=True)),
                ('module_cost_quote', models.CharField(blank=True, max_length=255, null=True)),
                ('by_pass', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('valid', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'pel_psmt_request_modules',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bgrequestmodule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='businesscompanyreg',
            options={'managed': False, 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='encumbrance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='packagemodule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='psmtrequest',
            options={'managed': False, 'ordering': ['-pk', 'bg_dataset_name']},
        ),
        migrations.AlterModelOptions(
            name='shares',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='companyofficialdetails',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='main.businesscompanyreg'),
        ),
        migrations.RenameField(
            model_name='companyofficialdetails',
            old_name='company',
            new_name='business',
        ),
        migrations.DeleteModel(
            name='EncumbranceSecuredAmounts',
        ),
    ]
