# Generated by Django 3.2.3 on 2023-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_peluser_usr_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='psmtrequest',
            name='medium',
            field=models.CharField(default='portal', max_length=20),
        ),
    ]
