# Generated by Django 4.2.3 on 2023-07-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
