# Generated by Django 3.2.3 on 2023-07-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_psmtrequest_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgrequestmodule',
            name='request_ref_number',
            field=models.ForeignKey(db_column='request_ref_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', related_query_name='modules', to='main.psmtrequest', to_field='request_ref_number'),
        ),
    ]
