# Generated by Django 3.2.3 on 2023-07-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bgrequestmodule_request_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluser',
            name='usr_biller_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
