# Generated by Django 4.2.3 on 2023-07-10 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_formdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('permission', models.CharField(choices=[('create_request', 'Create Request'), ('view_request', 'View Request'), ('add_user', 'Add User'), ('view_user', 'View User'), ('create_batch_request', 'Create Batch Request'), ('view_batch_request', 'View Batch Request')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
