# Generated by Django 3.2.3 on 2023-07-14 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_peluser_usr_biller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluser',
            name='usr_date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
