# Generated by Django 4.2.3 on 2023-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_permissions_userhaspermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.CharField(max_length=200),
        ),
    ]
