# Generated by Django 3.2.3 on 2023-07-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_peluser_usr_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluser',
            name='usr_phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
