# Generated by Django 4.2.3 on 2023-07-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_adduser_company_adduser_role_alter_adduser_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='company',
            field=models.ForeignKey(null=True, db_column='company', on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL, to_field='client_company_id'),
        ),
    ]
