# Generated by Django 3.2.3 on 2023-07-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_peluser_usr_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluser',
            name='usr_profile',
            field=models.IntegerField(default=1),
        ),
    ]
