# Generated by Django 3.2.3 on 2023-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230718_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmessageresponse',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
