# Generated by Django 3.2.3 on 2023-07-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_helpmessageresponse_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmessage',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.helpsubject'),
        ),
        migrations.AlterField(
            model_name='helpmessageresponse',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.helpmessage'),
        ),
    ]
