# Generated by Django 4.2.3 on 2023-07-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_clientcompany_options_alter_pelclient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcompany',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pelclient',
            options={'managed': True},
        ),
    ]
