# Generated by Django 4.2.3 on 2023-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_pelclient_client_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelclient',
            name='client_company_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
