# Generated by Django 3.2.3 on 2023-07-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_pelclient_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelclient',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
